{
    "openapi": "3.0.2",
    "info": {
        "title": "Laravel",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http:\/\/localhost"
        }
    ],
    "paths": {
        "\/api\/me": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "自分の情報を取得する。",
                "description": "詳細コメント"
            }
        },
        "\/api\/users\/{user}": {
            "get": {
                "summary": "ユーザー取得。",
                "parameters": [
                    {
                        "name": "user",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ]
            }
        }
    },
    "tags": [
        {
            "name": "user",
            "description": "Application users"
        }
    ]
}
